# Generated by Django 4.0.1 on 2022-02-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'contact_tbl',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('customer_picture', models.FileField(blank=True, upload_to='photos')),
                ('is_login', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'customer_tbl',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('product_price', models.CharField(blank=True, max_length=50)),
                ('product_desc', models.CharField(blank=True, max_length=50)),
                ('product_picture', models.ImageField(blank=True, upload_to='products/')),
            ],
            options={
                'db_table': 'products_tbl',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('order_date', models.DateField(blank=True)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('customer_obj', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Mandi.customer')),
                ('product_obj', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Mandi.products')),
            ],
            options={
                'db_table': 'order_tbl',
            },
        ),
    ]
