# Generated by Django 4.0.1 on 2022-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_fname', models.CharField(max_length=25)),
                ('customer_lname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('customer_picture', models.FileField(default='img1', upload_to='profile_pic')),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
    ]
